# Configuration AWS
aws_region: us-east-1
vpc_id: "{{ ansible_env.AWS_VPC_ID | default(omit) }}"
subnet_id: "{{ ansible_env.AWS_SUBNET_ID | default(omit) }}"

# Configuration des instances
instance_type: t3.micro
debian_ami_id: "ami-0f9c27b471bdcd702"
webdev_key_name: "vockey"

# Identification du projet
project_tag: "webdev-lab"

# Security Groups
bastion_sg_name: "{{ project_tag }}-bastion-sg"
web_sg_name: "{{ project_tag }}-web-sg"
db_sg_name: "{{ project_tag }}-db-sg"

# CIDR autorisés
ssh_cidr: "0.0.0.0/0"           # Accès SSH au bastion
web_http_cidr: "0.0.0.0/0"      # Accès HTTP aux serveurs web
phpmyadmin_cidr: "0.0.0.0/0"    # Accès phpMyAdmin

# Configuration SSH de base
ansible_user: admin
ansible_ssh_private_key_file: "/home/admin/.ssh/labsuser.pem"

# Configuration Base de données
db_name: "Test1"
db_user: "admin"
db_password: "IG2IUser"         # À changer en production !
db_port: 3306

ansible_ssh_common_args: >-
  -o StrictHostKeyChecking=no 
  -o UserKnownHostsFile=/dev/null 
  -o ForwardAgent=yes 
  -o BatchMode=yes 
  -o ConnectTimeout=60 
  -o ServerAliveInterval=30

