aws_region: us-east-1
debian_ami_id: "ami-0f9c27b471bdcd702"
instance_type: t3.micro
webdev_key_name: "labsuser"
ansible_user: admin
ansible_ssh_private_key_file: "/home/ec2-user/.ssh/labsuser.pem"
bastion_sg_name: "webdev-bastion-sg"
web_sg_name: "webdev-web-sg"
db_sg_name: "webdev-db-sg"
ssh_cidr: "0.0.0.0/0"
db_name: "Test1"
db_user: "admin"
db_password: "IG2IUser"
db_port: 3306
phpmyadmin_container_name: "myadmin"
dev_group: "admin"
infra_state: "present"
