aws_region: us-east-1
debian_ami_id: "ami-xxxxxxxxxxxxxxxxx"   # <-- remplace par l AMI Debian
instance_type: t3.micro
webdev_key_name: "labsuser"
ansible_user: admin
ansible_ssh_private_key_file: "/home/ec2-user/.ssh/labsuser.pem"
webdev_sg_name: "webdev-lab-sg"
ssh_cidr: "0.0.0.0/0"
db_name: "Test1"
db_user: "admin"
db_password: "IG2IUser"
db_port: 3306
phpmyadmin_container_name: "myadmin"
dev_group: "admin"
infra_state: "present"
