---
# Database configuration
db_name: "Test1"
db_user: "admin"
db_password: "IG2IUser"
db_port: 3306

# SSH configuration for DB servers
ansible_ssh_common_args: >-
  -o StrictHostKeyChecking=no 
  -o UserKnownHostsFile=/dev/null 
  -o ForwardAgent=yes 
  -o BatchMode=yes
  -o ConnectTimeout=60
  -o ServerAliveInterval=30
  -o ProxyCommand="ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o IdentityFile={{ ansible_ssh_private_key_file }} -W %h:%p -q {{ ansible_user }}@{{ hostvars[groups['tag_Role_Bastion'][0]].public_ip_address }}"
