---
ansible_ssh_common_args: >-
  -o StrictHostKeyChecking=no 
  -o UserKnownHostsFile=/dev/null 
  -o ForwardAgent=yes 
  -o BatchMode=yes
  -o ConnectTimeout=60
  -o ServerAliveInterval=30
  -o ProxyCommand="ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i {{ ansible_ssh_private_key_file }} -W %h:%p -q {{ ansible_user }}@{{ hostvars[groups['tag_Role_Bastion'][0]]['public_ip_address'] }}"
