- name: restart apache
  ansible.builtin.service:
    name: apache2
    state: restarted
  register: apache_restart
  ignore_errors: yes

- name: check apache error
  ansible.builtin.command: systemctl status apache2
  when: apache_restart is failed
  register: apache_status
  changed_when: false
